/**
 * Fragment shader for lightmap-based scene lighting.
 *
 * Uses worldView rectangle (top-left + size in world pixels) to map
 * fragment position to world coordinates. This accounts for scroll,
 * zoom, and any scale mode automatically.
 */
export const lightmapFragSource = [
  '#pragma phaserTemplate(shaderName)',
  'precision mediump float;',
  '',
  'uniform sampler2D uMainSampler;',
  'uniform sampler2D uLightmapSampler;',
  'uniform sampler2D uVisibilitySampler;',
  '',
  'uniform vec2 uWorldViewPos;',     // world position of camera top-left (pixels)
  'uniform vec2 uWorldViewSize;',    // world area visible (pixels), accounts for zoom
  'uniform vec2 uMapSize;',          // map dimensions in tiles
  'uniform float uTileSize;',
  'uniform float uTime;',
  'uniform vec3 uSeenTint;',
  'uniform float uLightScale;',
  'uniform float uRevealAll;',
  'uniform float uDebugMode;',  // 0=normal, 1=lightmap RGB, 2=visibility, 3=light intensity
  '',
  'varying vec2 outTexCoord;',
  '',
  'void main() {',
  '    vec4 scene = texture2D(uMainSampler, outTexCoord);',
  '',
  '    // outTexCoord.y=0 is screen-bottom (GL convention);',
  '    // worldView.y is the top of the visible area, so flip Y.',
  '    vec2 worldPixel = vec2(',
  '        uWorldViewPos.x + outTexCoord.x * uWorldViewSize.x,',
  '        uWorldViewPos.y + (1.0 - outTexCoord.y) * uWorldViewSize.y',
  '    );',
  '    vec2 tilePos = worldPixel / uTileSize;',
  '',
  '    vec2 tileUV = tilePos / uMapSize;',
  '',
  '    if (tileUV.x < 0.0 || tileUV.x > 1.0 || tileUV.y < 0.0 || tileUV.y > 1.0) {',
  '        gl_FragColor = scene;',
  '        return;',
  '    }',
  '',
  '    // Debug visualizations',
  '    if (uDebugMode > 0.5) {',
  '        vec3 lraw = texture2D(uLightmapSampler, tileUV).rgb;',
  '        vec3 vdata = texture2D(uVisibilitySampler, tileUV).rgb;',
  '        if (uDebugMode < 1.5) {',
  '            gl_FragColor = vec4(lraw * uLightScale, 1.0);',
  '            return;',
  '        } else if (uDebugMode < 2.5) {',
  '            float vr = vdata.r;',
  '            vec3 vc = vr < 0.1 ? vec3(0.6, 0.0, 0.0)',
  '                    : vr < 0.75 ? vec3(0.7, 0.7, 0.0)',
  '                    : vec3(0.0, 0.7, 0.0);',
  '            gl_FragColor = vec4(mix(scene.rgb * 0.3, vc, 0.7), 1.0);',
  '            return;',
  '        } else if (uDebugMode < 3.5) {',
  '            float intensity = dot(lraw * uLightScale, vec3(0.299, 0.587, 0.114));',
  '            vec3 heat;',
  '            if (intensity < 0.2) heat = mix(vec3(0.0), vec3(0.0, 0.0, 1.0), intensity / 0.2);',
  '            else if (intensity < 0.4) heat = mix(vec3(0.0, 0.0, 1.0), vec3(0.0, 1.0, 1.0), (intensity - 0.2) / 0.2);',
  '            else if (intensity < 0.6) heat = mix(vec3(0.0, 1.0, 1.0), vec3(0.0, 1.0, 0.0), (intensity - 0.4) / 0.2);',
  '            else if (intensity < 0.8) heat = mix(vec3(0.0, 1.0, 0.0), vec3(1.0, 1.0, 0.0), (intensity - 0.6) / 0.2);',
  '            else heat = mix(vec3(1.0, 1.0, 0.0), vec3(1.0, 0.0, 0.0), (intensity - 0.8) / 0.2);',
  '            gl_FragColor = vec4(mix(scene.rgb * 0.2, heat, 0.8), 1.0);',
  '            return;',
  '        } else {',
  '            int ft = int(vdata.b * 255.0 + 0.5);',
  '            vec3 fc = ft == 1 ? vec3(1.0, 0.3, 0.0)',
  '                    : ft == 2 ? vec3(0.0, 0.8, 1.0)',
  '                    : ft == 3 ? vec3(1.0, 0.0, 1.0)',
  '                    : vec3(0.0);',
  '            gl_FragColor = vec4(mix(scene.rgb * 0.3, fc, ft > 0 ? 0.8 : 0.0), 1.0);',
  '            return;',
  '        }',
  '    }',
  '',
  '    vec2 visData = texture2D(uVisibilitySampler, tileUV).rg;',
  '    float vis = visData.r;',
  '    float tileType = visData.g;',  // 0=VOID, ~0.5=FLOOR, 1=WALL
  '',
  '    // VOID (space) — pass through scene unmodified, same as out-of-bounds',
  '    if (tileType < 0.1) {',
  '        gl_FragColor = scene;',
  '        return;',
  '    }',
  '',
  '    // UNSEEN — dark, unknown',
  '    if (uRevealAll < 0.5 && vis < 0.1) {',
  '        gl_FragColor = vec4(scene.rgb * 0.03, scene.a * 0.15);',
  '        return;',
  '    }',
  '',
  '    // SEEN flag — will desaturate after lighting',
  '    float isSeen = (uRevealAll < 0.5 && vis < 0.75) ? 1.0 : 0.0;',
  '',
  '    int flickerType = int(texture2D(uVisibilitySampler, tileUV).b * 255.0 + 0.5);',
  '    vec3 light = texture2D(uLightmapSampler, tileUV).rgb * uLightScale;',
  '',
  '    if (flickerType == 1) {',
  '        // Fire: per-tile random flicker (no spatial waves)',
  '        // Hash tile index to get a unique seed per tile',
  '        float seed = fract(sin(dot(floor(tilePos), vec2(127.1, 311.7))) * 43758.5453);',
  '        float f = sin(uTime * 9.0 + seed * 6.28) * 0.12',
  '               + sin(uTime * 14.0 + seed * 41.0) * 0.10',
  '               + sin(uTime * 23.0 + seed * 97.0) * 0.06;',
  '        float intensity = 0.88 + f;',
  '        vec3 warm = vec3(1.0 + f * 0.4, 1.0 - abs(f) * 0.2, 1.0 - f * 1.2);',
  '        light *= intensity * warm;',
  '    } else if (flickerType == 2) {',
  '        // Broken: intermittent cuts like a bad neon',
  '        float t = uTime * 1.5 + tilePos.x * 0.3 + tilePos.y * 0.7;',
  '        float buzz = step(0.92, fract(sin(floor(t * 4.0)) * 43758.5453));',
  '        float flut = step(0.7, fract(sin(floor(t * 17.0)) * 23421.631));',
  '        light *= 1.0 - buzz * 0.85 - flut * 0.3;',
  '    } else if (flickerType == 3) {',
  '        // Pulse: gentle sine throb',
  '        light *= 0.85 + 0.15 * sin(uTime * 3.0 + tilePos.x + tilePos.y);',
  '    }',
  '',
  '    // Wall quadrant lighting: walls receive light from neighbors.',
  '    // Each pixel blends the 4 cardinal neighbors based on sub-tile position,',
  '    // so a hull wall shows interior light on one half and starlight on the other.',
  '    if (tileType > 0.9) {',
  '        vec2 texel = vec2(1.0) / uMapSize;',
  '        vec2 sub = fract(tilePos);',
  '        vec3 lN = texture2D(uLightmapSampler, tileUV + vec2(0.0, -texel.y)).rgb * uLightScale;',
  '        vec3 lS = texture2D(uLightmapSampler, tileUV + vec2(0.0,  texel.y)).rgb * uLightScale;',
  '        vec3 lW = texture2D(uLightmapSampler, tileUV + vec2(-texel.x, 0.0)).rgb * uLightScale;',
  '        vec3 lE = texture2D(uLightmapSampler, tileUV + vec2( texel.x, 0.0)).rgb * uLightScale;',
  '        vec3 blended = mix(mix(max(lN, lW), max(lN, lE), sub.x),',
  '                           mix(max(lS, lW), max(lS, lE), sub.x), sub.y);',
  '        light = max(light, blended);',
  '    }',
  '',
  '    light = max(light, vec3(0.06));',
  '',
  '    // Extended Reinhard tone mapping (per-channel).',
  '    float Wp = 2.5;',
  '    float Wp2 = Wp * Wp;',
  '    vec3 mapped = light * (vec3(1.0) + light / Wp2) / (vec3(1.0) + light);',
  '',
  '    vec3 result = scene.rgb * mapped;',
  '',
  '    // SEEN — desaturate (remembered, not currently visible)',
  '    if (isSeen > 0.5) {',
  '        float luma = dot(result, vec3(0.299, 0.587, 0.114));',
  '        result = mix(result, vec3(luma), 0.65);',
  '    }',
  '',
  '    gl_FragColor = vec4(result, scene.a);',
  '}',
].join('\n');
