/**
 * Fragment shader for lightmap-based scene lighting.
 *
 * Uses worldView rectangle (top-left + size in world pixels) to map
 * fragment position to world coordinates. This accounts for scroll,
 * zoom, and any scale mode automatically.
 */
export const lightmapFragSource = [
  '#pragma phaserTemplate(shaderName)',
  'precision mediump float;',
  '',
  'uniform sampler2D uMainSampler;',
  'uniform sampler2D uLightmapSampler;',
  'uniform sampler2D uVisibilitySampler;',
  '',
  'uniform vec2 uWorldViewPos;',     // world position of camera top-left (pixels)
  'uniform vec2 uWorldViewSize;',    // world area visible (pixels), accounts for zoom
  'uniform vec2 uMapSize;',          // map dimensions in tiles
  'uniform float uTileSize;',
  'uniform float uTime;',
  'uniform vec3 uSeenTint;',
  'uniform float uLightScale;',
  'uniform float uRevealAll;',
  '',
  'varying vec2 outTexCoord;',
  '',
  'void main() {',
  '    vec4 scene = texture2D(uMainSampler, outTexCoord);',
  '',
  '    if (uRevealAll > 0.5) {',
  '        gl_FragColor = scene;',
  '        return;',
  '    }',
  '',
  '    vec2 worldPixel = uWorldViewPos + outTexCoord * uWorldViewSize;',
  '    vec2 tilePos = worldPixel / uTileSize;',
  '',
  '    // UV for both textures — same coordinate, different filtering',
  '    vec2 tileUV = tilePos / uMapSize;',
  '',
  '    if (tileUV.x < 0.0 || tileUV.x > 1.0 || tileUV.y < 0.0 || tileUV.y > 1.0) {',
  '        gl_FragColor = scene;',
  '        return;',
  '    }',
  '',
  '    float vis = texture2D(uVisibilitySampler, tileUV).r;',
  '',
  '    if (vis < 0.1) {',
  '        gl_FragColor = vec4(scene.rgb * 0.03, scene.a * 0.15);',
  '        return;',
  '    }',
  '',
  '    if (vis < 0.75) {',
  '        gl_FragColor = vec4(scene.rgb * uSeenTint, scene.a);',
  '        return;',
  '    }',
  '',
  '    vec3 light = texture2D(uLightmapSampler, tileUV).rgb * uLightScale;',
  '    light = max(light, vec3(0.06));',
  '    vec3 result = scene.rgb * light;',
  '    vec3 excess = max(light - vec3(1.0), vec3(0.0));',
  '    result += excess * 0.4;',
  '    gl_FragColor = vec4(result, scene.a);',
  '}',
].join('\n');
